---
# playbook.yml
- name: 'install dart'
  hosts: default
  become: true

  tasks:
    - name: 'download package information'
      command: |
        sudo apt-get update
    - name: 'install APT transport'
      command: |
        sudo apt-get install apt-transport-https
    - name: 'download signing key'
      command: |
        wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | \
        sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
    - name: 'copy signing key'
      command: |
        echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' | \
        sudo tee /etc/apt/sources.list.d/dart_stable.list
    - name: 're-download package information'
      command: |
        sudo apt-get update
    - name: 'install dart'
      command: |
        sudo apt-get install dart
    - name: 'update path'
      command: |
        echo 'export PATH="$PATH:/usr/lib/dart/bin"' >> ~/.profile
    - name: 'version'
      command: |
        dart --version
